version: "3.8"

services:
  db:
    image: postgres:17
    container_name: cortex_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cortex_auth
    ports:
      - "127.0.0.1:5400:5432"
      # - "5400:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
